// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartBikeTracker.Infrastructure;

#nullable disable

namespace SmartBikeTracker.Infrastructure.Migrations
{
    [DbContext(typeof(SmartBikeDbContext))]
    partial class SmartBikeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartBikeTracker.Domain.Entities.Bike", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Bikes");
                });

            modelBuilder.Entity("SmartBikeTracker.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BikeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("SmartBikeTracker.Domain.Entities.Bike", b =>
                {
                    b.OwnsOne("SmartBikeTracker.Domain.Entities.Battery", "Battery", b1 =>
                        {
                            b1.Property<Guid>("BikeId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Percentage")
                                .HasColumnType("integer");

                            b1.HasKey("BikeId");

                            b1.ToTable("Bikes");

                            b1.WithOwner()
                                .HasForeignKey("BikeId");
                        });

                    b.OwnsOne("SmartBikeTracker.Domain.Entities.ChainSensor", "ChainSensor", b1 =>
                        {
                            b1.Property<Guid>("BikeId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("RequiresMaintenance")
                                .HasColumnType("boolean");

                            b1.HasKey("BikeId");

                            b1.ToTable("Bikes");

                            b1.WithOwner()
                                .HasForeignKey("BikeId");
                        });

                    b.Navigation("Battery")
                        .IsRequired();

                    b.Navigation("ChainSensor")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
